export { DEMO_EMAIL, DEMO_PASSWORD, DEMO_PHONE, DEMO_USER_ID, AUTH_ERROR } from './constants'
export {
  ageFromDob,
  ageToDob,
  createId,
  createMember,
  digitsOnly,
  emptyRecords,
  formatHeight,
  formatPhone,
  formatWeight,
  formatIndianPhone,
  formatNepalPhone,
  indianMobile,
  nepalMobile,
  initialsFromName,
  isPatientProfileComplete,
  isValidPhone,
  membersForBooking,
  normalizeEmail,
  normalizeHeight,
  normalizePhone,
  normalizeWeight,
  numericValue,
  parseMeasurement,
  phoneDigits,
  phoneInput,
  profileView,
  publicUser,
  selfMember,
} from './models'
export { validateLogin, validateRegister, validateLoginFields, validateRegisterFields, validatePasswordFields, firstInvalidField, isValidEmail, isValidIndianMobile, isValidNepalMobile, isStrongPassword, passwordStrength } from './validation'
export {
  addFamilyMember,
  appendPaymentHistory,
  attachAuthenticatedUser,
  checkPhoneDuplicate,
  completeSelfProfile,
  currentUser,
  ensureDemoUser,
  getUserReviews,
  getUserSnapshot,
  hydrateProfileFromSupabase,
  isInsightSaved,
  loginWithPassword,
  logout,
  markPhoneVerified,
  patchCurrentUser,
  registerAccount,
  removeEmergencyContact,
  removeHealthItem,
  removeInsurancePolicy,
  removeSavedAddress,
  removeUserReview,
  setGoogleBirthday,
  subscribeUserStore,
  toggleSavedInsight,
  updatePersonalProfile,
  upsertEmergencyContact,
  upsertHealthItem,
  upsertInsurancePolicy,
  upsertSavedAddress,
  upsertUserReview,
} from './store'
export {
  ATTACH_GROUPS,
  HEALTH_SECTIONS,
  LIST_SECTIONS,
  attachedHealthItems,
  displayHealthDate,
  emptyHealth,
  findHealthItem,
  flattenHealth,
  healthItemMeta,
  healthMemoryTimeline,
  itemsForAttachGroup,
  listItemMeta,
  listItemTitle,
} from './health'
export { UserProvider, useUser, getActiveUser } from './UserProvider'
