export { DEMO_EMAIL, DEMO_PASSWORD, DEMO_PHONE, DEMO_USER_ID, AUTH_ERROR } from './constants'
export {
  ageFromDob,
  createId,
  createMember,
  digitsOnly,
  emptyRecords,
  formatIndianPhone,
  indianMobile,
  initialsFromName,
  isPatientProfileComplete,
  membersForBooking,
  normalizeEmail,
  profileView,
  publicUser,
  selfMember,
} from './models'
export { validateLogin, validateRegister, validateLoginFields, validateRegisterFields, isValidEmail, isValidIndianMobile, isStrongPassword } from './validation'
export {
  addFamilyMember,
  appendPaymentHistory,
  completeSelfProfile,
  currentUser,
  ensureDemoUser,
  getUserReviews,
  getUserSnapshot,
  isInsightSaved,
  loginWithPassword,
  logout,
  markAllNotificationsRead,
  markNotificationRead,
  patchCurrentUser,
  pushNotification,
  registerAccount,
  removeEmergencyContact,
  removeHealthItem,
  removeInsurancePolicy,
  removeSavedAddress,
  removeUserReview,
  subscribeUserStore,
  toggleSavedInsight,
  updatePersonalProfile,
  upsertEmergencyContact,
  upsertHealthItem,
  upsertInsurancePolicy,
  upsertSavedAddress,
  upsertUserReview,
} from './store'
export {
  ATTACH_GROUPS,
  HEALTH_SECTIONS,
  LIST_SECTIONS,
  attachedHealthItems,
  displayHealthDate,
  emptyHealth,
  findHealthItem,
  flattenHealth,
  healthItemMeta,
  itemsForAttachGroup,
  listItemMeta,
  listItemTitle,
} from './health'
export { UserProvider, useUser, getActiveUser } from './UserProvider'
